### ISSUE TITLE
Config: Trim Pattern/Material List

### ISSUE THREAD

**Issue by 256smash** [Imajo24I/Mob-Armor-Trims-1.20.1#3]
### Feature description.

Hello!

I have a feature request for the config: add a **List** for custom trims, not only of vanilla but also of other modified trims (Materials and Patterns).

It would be convenient for modpack creators who want more creativity!

**Comment by Imajo24I** [comment]
Good idea of a new feature, but I have some questions: 

- If enabled, would this replace the  normal system of giving mobs trims, meaning mobs would only be able to get trims out of this custom List?

- Would the whole armor consist of this trim, or does every piece have a different trim?

**Comment by 256smash** [comment]
That's exactly what I was thinking! I also think to need to add "Different Trims" (Boolean, will default to "false").

But as for the first question, I think yes. :-)

**Comment by Imajo24I** [comment]
I'll look into adding this in one or two days.

**Comment by Imajo24I** [comment]
Hey there, sorry it took me so long, but I haven't had much time the past few days. 
I got the new system implemented.

To use it, make sure to have it enabled in the `General` section of the config screen. Then you can add custom trims under the `Custom Trims` section. It's a bit weird to add trims rn, but I'll try to improve it. Read the description of the config option, to figure out how to add a trim.

The prerelease is currently only avaible for Fabric 1.20.1. You can find it [here](https://github.com/Imajo24I/Mob-Armor-Trims/releases).
Also note, that the prerelease now uses [Yet Another Config Lib](https://modrinth.com/mod/yacl) and no longer uses Cloth Config API, as Cloth Config API doesn't have as many features, which would have made the config screen even worse, if I hadn't switched.

Before I release this, I'll improve some stuff, including the config screen, and port this to newer versions and modloaders.
If you find any issues or have questions, please let me know.

**Comment by Imajo24I** [comment]
Hey there, this feature has been released within the new 2.1.0 release. You can find it [here](https://modrinth.com/mod/mob-armor-trims/versions).
