### ISSUE TITLE
The mobs dont spawn with armor at all

### ISSUE THREAD

**Issue by sigmaskibussysigmakai** [Imajo24I/Mob-Armor-Trims-1.20.1#6]
### Describe the bug

The mobs that naturally spawn have no armor

### Steps to reproduce

Any mod that you are aware of that disrupts the mod from working?

### Expected behavior

The skeletons, zombies and other humanoid mobs spawn with trimmed armor

### Mod Setup

Version 1.21 Fabric

### Additional context

Ive had all the optional mods installed and it still doesn't work

**Comment by Imajo24I** [comment]
In easy difficulty, mobs will never have armor, and in medium and hard difficulty, mobs will also only have a 0-15% chance of having armor, depending on the local difficulty. 

This behaviour isn't changed by the mod, it only applies trims to armor pieces, that the vanilla game already gave the mob.

At the start of a new world, even in hard difficulty, the chances of armor are really low, so thats why you might not see mobs with armor.

To test if everything truly works, you could set up a commandblock that repeatedly spawns skeletons and see if skeletons with armor spawn.
